name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  intl: any
  
  google_fonts: ^6.2.1
  go_router: ^14.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  firebase_ui_auth: ^1.15.0
  firebase_ui_localizations: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/codelab.png

